#!/bin/bash
set -e

ip=$1       # Interface IP address
repo=$2     # OVS repository
branch=$3   # Repository branch

# Enable password-less SSH between nodes
cat /vagrant/id_rsa.pub >> /home/vagrant/.ssh/authorized_keys
cat /vagrant/id_rsa >> /home/vagrant/.ssh/id_rsa
chown -R vagrant:vagrant /home/vagrant/.ssh
chmod 600 /home/vagrant/.ssh/id_rsa

# Work around vagrant 1.9.1 issue #8142
sudo ifup eth1 > /dev/null || true

# Build and install OVN
/vagrant/build_ovn $repo $branch

# Start OVN central services
sudo systemctl enable ovn-northd
sudo systemctl start ovn-northd

# Configure OVN central services
sudo ovn-nbctl init
sudo ovn-nbctl set-ssl /vagrant/pki/ovnnb-privkey.pem  /vagrant/pki/ovnnb-cert.pem /vagrant/pki/switchca/cacert.pem
sudo ovn-nbctl set-connection pssl:6641

sudo ovn-sbctl init
sudo ovn-sbctl set-ssl /vagrant/pki/ovnsb-privkey.pem  /vagrant/pki/ovnsb-cert.pem /vagrant/pki/switchca/cacert.pem
sudo ovn-sbctl set-connection role=ovn-controller pssl:6642
sudo ovs-vsctl set open . external-ids:ovn-remote=ssl:127.0.0.1:6642

