#!/bin/bash
set -e

ip=$1       # Interface IP address
repo=$2     # OVS repository
branch=$3   # Repository branch

# Enable password-less SSH between nodes
cat /vagrant/id_rsa.pub >> /home/vagrant/.ssh/authorized_keys
cat /vagrant/id_rsa >> /home/vagrant/.ssh/id_rsa
chown -R vagrant:vagrant /home/vagrant/.ssh
chmod 600 /home/vagrant/.ssh/id_rsa

# Work around vagrant 1.9.1 issue #8142
sudo ifup eth1 > /dev/null || true

# Build and install OVN
/vagrant/build_ovn $repo $branch

# Start OVN central services
sudo systemctl enable ovn-northd
sudo systemctl start ovn-northd

# Start OVN and OVS services
sudo systemctl enable openvswitch
sudo systemctl start openvswitch

sudo systemctl enable ovn-controller
sudo systemctl start ovn-controller

# Configure OVN central services
sudo ovn-nbctl init
sudo ovn-nbctl set-connection ptcp:6641

sudo ovn-sbctl init
sudo ovn-sbctl set-connection ptcp:6642

sudo ovs-vsctl --no-wait init
sudo ovs-vsctl --no-wait set open_vswitch . system-type="vagrant"
sudo ovs-vsctl --no-wait set open_vswitch . external-ids:system-id=central
sudo ovs-vsctl --no-wait set open_vswitch . external-ids:hostname=central

sudo ovs-vsctl --no-wait set open_vswitch . external-ids:ovn-bridge="br-int"
sudo ovs-vsctl --no-wait set open_vswitch . external-ids:ovn-encap-ip=127.0.0.1
sudo ovs-vsctl --no-wait set open_vswitch . external-ids:ovn-encap-type="geneve"
sudo ovs-vsctl --no-wait set open_vswitch . external-ids:ovn-remote=tcp:127.0.0.1:6642
