ovn_repo         = "https://github.com/openvswitch/ovs.git"
ovn_branch       = "master"
ovn_pkg_dir      = "/vagrant/pkgs"

ovn_cfg = [
    {
     :name => "central",
     :box => "centos/7",
     :autostart => true,
     :host_name  => "central.ovn.dev",
     :ip => "192.168.33.11",
     :memory => 1536,
     :cpus => 1,
     :mtu => 1500,
     :nic_type => "virtio",
     :nic0 => "eth0",
     :nic1 => "eth1",
     :dmz_network => "fd94:41f3:071a:9d54::1/64",
     :inside_network => "fd94:41f3:071a:9d55::1/64",
   },{
     :name => "compute1",
     :box => "centos/7",
     :autostart => true,
     :host_name  => "compute1.ovn.dev",
     :ip => "192.168.33.31",
     :memory => 512,
     :cpus => 1,
     :mtu => 1500,
     :nic_type => "virtio",
     :nic0 => "eth0",
     :nic1 => "eth1",
     :dmz_ip => "fd94:41f3:071a:9d54::2",
     :dmz_mac => "02:ac:10:ff:01:30",
     :dmz_vm => "vm1",
     :inside_ip => "fd94:41f3:071a:9d55::2",
     :inside_mac => "02:ac:10:ff:01:94",
     :inside_vm => "vm3",
   },{
     :name => "compute2",
     :box => "centos/7",
     :autostart => true,
     :host_name  => "compute2.ovn.dev",
     :ip => "192.168.33.32",
     :memory => 512,
     :cpus => 1,
     :mtu => 1500,
     :nic_type => "virtio",
     :nic0 => "eth0",
     :nic1 => "eth1",
     :dmz_ip => "fd94:41f3:071a:9d54::3",
     :dmz_mac => "02:ac:10:ff:01:31",
     :dmz_vm => "vm2",
     :inside_ip => "fd94:41f3:071a:9d55::3",
     :inside_mac => "02:ac:10:ff:01:95",
     :inside_vm => "vm4",
   }
]

Vagrant.configure("2") do |config|

  ovn_cfg.each do |server|

    if server[:name] == "central"
        is_primary = true
    else
        is_primary = false
    end

    config.vm.define server[:name], primary: is_primary, autostart: server[:autostart] do |node|
      config.ssh.insert_key = false
      config.ssh.shell = "bash -c 'BASH_ENV=/etc/profile exec bash'" # avoids 'stdin: is not a tty' error.
      node.vm.box = server[:box]
      node.vm.box_check_update = false

      ovn_cfg.each do |entry|
          node.vm.provision "shell", inline: %Q(sudo sh -c "echo \\\"#{entry[:ip]} #{entry[:name]}\\\" >> /etc/hosts")
      end

      node.vm.hostname = server[:host_name]
      node.vm.network :private_network, ip: server[:ip]

      config.vm.provider "libvirt" do |domain|
        domain.memory = server[:memory]
        domain.cpus = server[:cpus]
        domain.nic_model_type = server[:nic_type]
      end

      setup_args = "#{server[:ip]} #{ovn_repo} #{ovn_branch}"
      if server[:name] == "central"
          node.vm.provision "shell", path: "setup_central", :args => "#{setup_args}" 
          node.vm.provision "shell", path: "setup_routing_central", :args => "#{server[:dmz_network]} #{server[:inside_network]}"
      else # compute node
          node.vm.provision "shell", path: "setup_controller", :args => "#{setup_args}"
          node.vm.provision "shell", path: "setup_routing_controller", :args => "#{server[:dmz_ip]} #{server[:dmz_mac]} #{server[:inside_ip]} #{server[:inside_mac]} #{server[:dmz_vm]} #{server[:inside_vm]}"
      end
    end
  end
end
