ovn_repo         = "https://github.com/openvswitch/ovs.git"
ovn_branch       = "master"
ovn_pkg_dir      = "/vagrant/pkgs"

ovn_cfg = [
    {
     :name => "central",
     :box => "centos/7",
     :autostart => true,
     :host_name  => "central.ovn.dev",
     :ip => "192.168.33.11",
     :memory => 1536,
     :cpus => 1,
     :mtu => 1500,
     :nic_type => "virtio",
     :nic0 => "eth0",
     :nic1 => "eth1",
   }
]

Vagrant.configure("2") do |config|

  ovn_cfg.each do |server|

    if server[:name] == "central"
        is_primary = true
    else
        is_primary = false
    end

    config.vm.define server[:name], primary: is_primary, autostart: server[:autostart] do |node|
      config.ssh.insert_key = false
      config.ssh.shell = "bash -c 'BASH_ENV=/etc/profile exec bash'" # avoids 'stdin: is not a tty' error.
      node.vm.box = server[:box]
      node.vm.box_check_update = false

      ovn_cfg.each do |entry|
          node.vm.provision "shell", inline: %Q(sudo sh -c "echo \\\"#{entry[:ip]} #{entry[:name]}\\\" >> /etc/hosts")
          node.vm.provision "shell", inline: %Q(sudo setenforce 0)
      end

      node.vm.hostname = server[:host_name]
      node.vm.network :private_network, ip: server[:ip]

      config.vm.provider "libvirt" do |domain|
        domain.memory = server[:memory]
        domain.cpus = server[:cpus]
        domain.nic_model_type = server[:nic_type]
      end

      setup_args = "#{server[:ip]} #{ovn_repo} #{ovn_branch}"
      if server[:name] == "central"
          node.vm.provision "shell", path: "setup_central", :args => "#{setup_args}" 
          node.vm.provision "shell", path: "setup_routing_central"
      else # compute node
          node.vm.provision "shell", path: "setup_controller", :args => "#{setup_args}"
      end
    end
  end
end
